<a href="https://colab.research.google.com/github/saadmansakib75/Data_Science-and-Machine-Learnig/blob/main/Stratification(dataset_shuffling).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd

In [27]:
df = pd.DataFrame({
    'Feature' : np.arange(1,11),
    'Target' : np.array([1,1,1,2,2,2,2,3,3,3])
})
df

   Feature  Target
0        1       1
1        2       1
2        3       1
3        4       2
4        5       2
5        6       2
6        7       2
7        8       3
8        9       3
9       10       3

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df[['Feature']],
    df['Target'],
    random_state= 43,
    stratify= df['Target']
)

In [34]:
pd.concat([X_train, y_train], axis=1)

   Feature  Target
8        9       3
1        2       1
3        4       2
4        5       2
7        8       3
2        3       1
5        6       2

In [35]:
pd.concat([X_test, y_test], axis=1)

   Feature  Target
0        1       1
6        7       2
9       10       3